sudo: required
dist: trusty
before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - export MYSQL_APT_CONFIG_FILE=mysql-apt-config_0.7.2-1_all.deb
  - wget http://dev.mysql.com/get/$MYSQL_APT_CONFIG_FILE
  - sudo dpkg -i --force-confnew $MYSQL_APT_CONFIG_FILE
  - sudo apt-get -y update
  - sudo apt-get -qq install mysql-server-5.7
